# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DingDingClock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DingDingClock
  pod 'Masonry'
  pod 'NOVUtilities', :git => 'https://github.com/Jdb156158/NOVUtilities.git'
end
